name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16.1
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Check Spells
        run: yarn ci:spell
      - name: Check Format
        run: yarn ci:format
      - name: Check Types
        run: yarn ci:ts
