name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 날짜 생성
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Create .env
        run: |
          echo "${{ secrets.ENV }}" > ./.env

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: Docker 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: joosum.kr.ncr.ntruss.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          tags: joosum.kr.ncr.ntruss.com/joosum-frontend:${{ steps.date.outputs.date }}
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 날짜 생성
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: 배포
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: root
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            docker pull joosum.kr.ncr.ntruss.com/joosum-frontend:${{ steps.date.outputs.date }}
            docker stop frontend || true
            docker rm -f frontend 2>/dev/null || true
            docker run --rm -d -p 3000:3000 \
              --log-opt max-size=10k --log-opt max-file=3 \
              --name frontend joosum.kr.ncr.ntruss.com/joosum-frontend:${{ steps.date.outputs.date }}
